
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://18.230.144.119:5432/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/