
server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://ec2-18-230-115-62.sa-east-1.compute.amazonaws.com:5432/fornecedor
  jpa:
    hibernate:
      ddl-auto: update